# Generated by Django 3.1.3 on 2020-11-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Imagen'),
        ),
    ]
